includes:
  - https://github.com/terraform-ibm-modules/maximo-application-suite/reference-architecures

# Uncomment the following section if excluding files from translation.
# translation:
#  exclude:
#    byFilePath:
#      - file-dont-translate.md
#      - folder-dont-translate/
